#!/usr/bin/env python3
"""Scaffold a Django project using RAPID's horizontal layout.

    python new_rapid_project.py <name> [--dir PARENT] [--domain NOTE_DOMAIN]

Layout (see docs/adr/0001 in the generated project):

    <name>/
      config/                  generated by django-admin startproject, then patched
      <name>/data/             only model-holding app (models/, admin.py, migrations/)
      <name>/readers/          read-only business logic, one file per domain
      <name>/actions/          state-changing business logic, one file per domain
      <name>/interfaces/http/  thin function-based views + urls
      <name>/interfaces/management_commands/   registered only for command discovery

Stdlib only. Requires `uv` on PATH. config/ and manage.py come from `django-admin
startproject`, so settings match the installed Django version.
"""

import argparse
import re
import shutil
import subprocess
import sys
from pathlib import Path


def render(text: str, ctx: dict[str, str]) -> str:
    for key, value in ctx.items():
        text = text.replace("{{" + key + "}}", value)
    return text


TEMPLATES_DIR = Path(__file__).resolve().parent / "templates"


def render_tree(root: Path, ctx: dict[str, str]) -> int:
    """Copy templates/ into root, substituting __name__ in paths and {{name}} in contents."""
    count = 0
    for src in sorted(TEMPLATES_DIR.rglob("*")):
        if not src.is_file() or "__pycache__" in src.parts:
            continue
        rel = str(src.relative_to(TEMPLATES_DIR))
        for key, value in ctx.items():
            rel = rel.replace(f"__{key}__", value)
        dest = root / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(render(src.read_text(), ctx))
        count += 1
    return count


def to_identifier(name: str) -> str:
    ident = re.sub(r"[^0-9a-zA-Z_]", "_", name).strip("_").lower()
    if not ident or ident[0].isdigit():
        sys.exit(f"error: '{name}' cannot be made into a valid Python package name")
    return ident


def singular(word: str) -> str:
    return word[:-1] if word.endswith("s") and len(word) > 1 else word


def patch_settings(path: Path, pkg: str) -> None:
    """Register the two RAPID apps. Matches the list's closing bracket so quote style
    and Django version don't matter; fails loudly rather than half-patching."""
    text = path.read_text()
    m = re.search(r"^INSTALLED_APPS\s*=\s*\[.*?^\]", text, re.S | re.M)
    if not m:
        sys.exit(f"error: could not find INSTALLED_APPS in {path}")
    block = m.group(0)
    addition = f'    "{pkg}.data",\n    "{pkg}.interfaces.management_commands",\n'
    path.write_text(text.replace(block, block[:-1] + addition + "]", 1))


def patch_urls(path: Path, pkg: str) -> None:
    text = path.read_text()
    if "include" not in text.split("urlpatterns")[0]:
        text, n = re.subn(r"^from django\.urls import (.+)$", r"from django.urls import \1, include", text, count=1, flags=re.M)
        if not n:
            sys.exit(f"error: unexpected {path}")
    m = re.search(r"^urlpatterns\s*=\s*\[.*?^\]", text, re.S | re.M)
    if not m:
        sys.exit(f"error: could not find urlpatterns in {path}")
    block = m.group(0)
    path.write_text(text.replace(block, block[:-1] + f'    path("", include("{pkg}.interfaces.http.urls")),\n]', 1))


def run(cmd: list[str], cwd: Path) -> None:
    print("$", " ".join(cmd))
    subprocess.run(cmd, cwd=cwd, check=True)


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("name", help="project name (also used, snake_cased, as the top-level package)")
    p.add_argument("--dir", default=".", help="parent directory (default: cwd)")
    p.add_argument("--domain", default="notes", help="sample domain, plural (default: notes)")
    args = p.parse_args()

    pkg = to_identifier(args.name)
    domain = to_identifier(args.domain)
    domain_singular = singular(domain)
    ctx = {
        "name": args.name,
        "pkg": pkg,
        "domain": domain,
        "domain_singular": domain_singular,
        "Model": "".join(part.capitalize() for part in domain_singular.split("_")),
    }

    if not shutil.which("uv"):
        sys.exit("error: uv not found on PATH")
    root = Path(args.dir).expanduser().resolve() / args.name
    if root.exists():
        sys.exit(f"error: {root} already exists")
    root.mkdir(parents=True)

    # Let Django generate config/ + manage.py for the installed version, then patch.
    (root / "pyproject.toml").write_text(
        f'[project]\nname = "{args.name.lower().replace("_", "-")}"\nversion = "0.1.0"\n'
        'requires-python = ">=3.12"\ndependencies = []\n'
    )
    run(["uv", "add", "django"], root)
    run(["uv", "run", "django-admin", "startproject", "config", "."], root)
    patch_settings(root / "config" / "settings.py", pkg)
    patch_urls(root / "config" / "urls.py", pkg)

    print(f"wrote {render_tree(root, ctx)} files to {root}")

    run(["uv", "run", "python", "manage.py", "makemigrations", "data"], root)
    run(["uv", "run", "python", "manage.py", "check"], root)
    print(f"\ndone. cd {root} && uv run python manage.py migrate && uv run python manage.py runserver")


if __name__ == "__main__":
    main()
